heat_template_version: queens
parameters:
  image:
    type: string
  flavor:
    type: string
  key:
    type: string
  subnet:
    type: string
  db_password:
    type: string
  vol_size:
    type: number

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: vol_size }

  config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: |
            #!/bin/sh -x
            apt-get install -y postgresql
            sudo -u postgres createdb --locale=en_US.utf8 --encoding=UTF8 --template=template0 refwebapp
            sudo -u postgres psql -c "CREATE ROLE refwebapp WITH LOGIN PASSWORD '$db_password'; GRANT ALL ON DATABASE refwebapp TO refwebapp;"
          params:
            $db_password: { get_param: db_password }
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
      - subnet: { get_param: subnet }
      user_data_format: RAW
      user_data: { get_resource: config }
outputs:
  ip:
    value: { get_attr: [server, first_address ]}
  sqla_url:
    value:
      list_join:
      - ""
      - - "postgresql+pg8000://refwebapp:"
        - { get_param: db_password}
        - "@"
        - { get_attr: [ server, first_address ] }
        - ":5432/refwebapp"
