heat_template_version: queens
parameters:
  image:
    type: string
  flavor:
    type: string
  key:
    type: string
  subnet:
    type: string
  db_user:
    type: string
  db_password:
    type: string
  db_root_password:
    type: string
  vol_size:
    type: number

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: vol_size }

  config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: |
            #!/bin/sh
            echo running cloud-init script
            echo db root password is $db_root_password
            echo db user is $db_user
            echo db user pasword is $db_password
          params:
            $db_root_password: { get_param: db_root_password }
            $db_password: { get_param: db_password }
            $db_user: { get_param: db_user }
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
      - subnet: { get_param: subnet }
      user_data_format: RAW
      user_data: { get_resource: config }
outputs:
  ip:
    value: { get_attr: [server, first_address ]}
